theme: jekyll-theme-minimal
title: "Nina Thoni blabla"
# logo: "/assets/img/profile.jpg"  # Replace with your actual profile image path
show_downloads: False  # Hide download buttons for a cleaner look

# Custom Styles
include: ["assets/css/style.css"]

